# Generated by Django 5.1.4 on 2025-01-16 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_sellerprofile_banner_and_more"),
        ("uzum", "0002_product_productimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="name_ru",
        ),
        migrations.AddField(
            model_name="product",
            name="name_uz",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="users.store"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description_uz",
            field=models.TextField(blank=True, null=True),
        ),
    ]
