# Generated by Django 5.1.4 on 2025-01-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customeraccount_email_customeraccount_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellerprofile",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="description",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="store_address",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="store_name",
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("logo", models.ImageField(upload_to="seller-logos/")),
                ("banner", models.ImageField(upload_to="seller-banners/")),
                ("store_address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.sellerprofile",
                    ),
                ),
            ],
        ),
    ]
